"""QMIX: Monotonic Value Function Factorisation for Deep Multi-Agent RL.

Key idea: Q_total = f(Q_1, Q_2, ..., Q_n, state) where f is a mixing network
with non-negative weights (ensuring monotonicity), generated by hypernetworks
conditioned on the global state.
"""

import torch
import torch.nn as nn
import numpy as np
from pathlib import Path


class QMIXAgent(nn.Module):
    """Individual agent Q-network (DRQN-style with GRU)."""

    def __init__(self, obs_dim, n_actions, hidden_dim=64):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.fc1 = nn.Linear(obs_dim, hidden_dim)
        self.rnn = nn.GRUCell(hidden_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, n_actions)

    def forward(self, obs, hidden):
        """obs: (batch, obs_dim), hidden: (batch, hidden_dim)"""
        x = torch.relu(self.fc1(obs))
        h = self.rnn(x, hidden)
        q = self.fc2(h)
        return q, h

    def init_hidden(self, batch_size=1):
        return torch.zeros(batch_size, self.hidden_dim)


class MixingNetwork(nn.Module):
    """Mixing network that combines individual Q-values into Q_total.

    Uses hypernetworks conditioned on global state to generate weights.
    Weights are forced to be non-negative (via abs) to ensure monotonicity.
    """

    def __init__(self, n_agents, global_state_dim, mixing_dim=32):
        super().__init__()
        self.n_agents = n_agents

        # Hypernetwork for first layer weights
        self.hyper_w1 = nn.Sequential(
            nn.Linear(global_state_dim, mixing_dim),
            nn.ReLU(),
            nn.Linear(mixing_dim, n_agents * mixing_dim),
        )
        self.hyper_b1 = nn.Linear(global_state_dim, mixing_dim)

        # Hypernetwork for second layer weights
        self.hyper_w2 = nn.Sequential(
            nn.Linear(global_state_dim, mixing_dim),
            nn.ReLU(),
            nn.Linear(mixing_dim, mixing_dim),
        )
        self.hyper_b2 = nn.Sequential(
            nn.Linear(global_state_dim, mixing_dim),
            nn.ReLU(),
            nn.Linear(mixing_dim, 1),
        )

        self.mixing_dim = mixing_dim

    def forward(self, q_values, state):
        """
        q_values: (batch, n_agents) - individual Q values
        state: (batch, state_dim) - global state
        Returns: Q_total (batch, 1)
        """
        batch_size = q_values.size(0)
        q_values = q_values.view(batch_size, 1, self.n_agents)

        # First layer
        w1 = torch.abs(self.hyper_w1(state))
        w1 = w1.view(batch_size, self.n_agents, self.mixing_dim)
        b1 = self.hyper_b1(state).view(batch_size, 1, self.mixing_dim)
        hidden = torch.relu(torch.bmm(q_values, w1) + b1)

        # Second layer
        w2 = torch.abs(self.hyper_w2(state))
        w2 = w2.view(batch_size, self.mixing_dim, 1)
        b2 = self.hyper_b2(state).view(batch_size, 1, 1)
        q_total = torch.bmm(hidden, w2) + b2

        return q_total.squeeze(-1).squeeze(-1)


class QMIXReplayBuffer:
    """Experience replay buffer for QMIX."""

    def __init__(self, capacity=10000):
        self.capacity = capacity
        self.buffer = []
        self.position = 0

    def store_episode(self, episode):
        """Store a complete episode.

        episode: dict with keys obs, actions, rewards, next_obs, dones, state, next_state
        Each value is a list of per-timestep tensors.
        """
        if len(self.buffer) < self.capacity:
            self.buffer.append(None)
        self.buffer[self.position] = episode
        self.position = (self.position + 1) % self.capacity

    def sample(self, batch_size):
        indices = np.random.choice(len(self.buffer), batch_size, replace=True)
        return [self.buffer[i] for i in indices]

    def __len__(self):
        return len(self.buffer)


class QMIX:
    """QMIX trainer."""

    def __init__(
        self,
        obs_dim,
        global_state_dim,
        n_actions,
        n_agents,
        hidden_dim=64,
        mixing_dim=32,
        lr=5e-4,
        gamma=0.99,
        target_update_interval=200,
        epsilon_start=1.0,
        epsilon_end=0.05,
        epsilon_decay=5000,
        buffer_size=5000,
        batch_size=32,
        device="cpu",
    ):
        self.n_agents = n_agents
        self.n_actions = n_actions
        self.obs_dim = obs_dim
        self.gamma = gamma
        self.target_update_interval = target_update_interval
        self.batch_size = batch_size
        self.device = device

        # Epsilon-greedy
        self.epsilon_start = epsilon_start
        self.epsilon_end = epsilon_end
        self.epsilon_decay = epsilon_decay
        self.steps_done = 0

        # Shared agent network (parameter sharing)
        self.agent_net = QMIXAgent(obs_dim, n_actions, hidden_dim).to(device)
        self.target_agent_net = QMIXAgent(obs_dim, n_actions, hidden_dim).to(device)

        # Mixing network
        self.mixer = MixingNetwork(n_agents, global_state_dim, mixing_dim).to(device)
        self.target_mixer = MixingNetwork(n_agents, global_state_dim, mixing_dim).to(device)

        # Copy to targets
        self.target_agent_net.load_state_dict(self.agent_net.state_dict())
        self.target_mixer.load_state_dict(self.mixer.state_dict())

        self.params = list(self.agent_net.parameters()) + list(self.mixer.parameters())
        self.optimizer = torch.optim.Adam(self.params, lr=lr)

        self.replay_buffer = QMIXReplayBuffer(buffer_size)
        self.update_count = 0

    def get_epsilon(self):
        eps = self.epsilon_end + (self.epsilon_start - self.epsilon_end) * \
              np.exp(-self.steps_done / self.epsilon_decay)
        return eps

    @torch.no_grad()
    def act(self, obs, hidden_states, deterministic=False):
        """Select actions for all agents.

        obs: (n_agents, obs_dim)
        hidden_states: (n_agents, hidden_dim)

        Returns: actions (n_agents,), new_hidden (n_agents, hidden_dim)
        """
        actions = []
        new_hiddens = []

        for i in range(self.n_agents):
            q_values, h = self.agent_net(
                obs[i].unsqueeze(0), hidden_states[i].unsqueeze(0)
            )
            q_values = q_values.squeeze(0)
            h = h.squeeze(0)

            if deterministic:
                action = q_values.argmax()
            else:
                eps = self.get_epsilon()
                if np.random.random() < eps:
                    action = torch.tensor(np.random.randint(0, self.n_actions))
                else:
                    action = q_values.argmax()

            actions.append(action)
            new_hiddens.append(h)

        self.steps_done += 1
        return torch.stack(actions), torch.stack(new_hiddens)

    def get_q_values(self, obs, hidden):
        """Get Q-values for all agents. Used by FGSM attack.

        obs: (n_agents, obs_dim)
        hidden: (n_agents, hidden_dim)
        Returns: q_values (n_agents, n_actions)
        """
        q_list = []
        for i in range(self.n_agents):
            q, _ = self.agent_net(obs[i].unsqueeze(0), hidden[i].unsqueeze(0))
            q_list.append(q.squeeze(0))
        return torch.stack(q_list)

    def update(self):
        """Sample batch and do one gradient step."""
        if len(self.replay_buffer) < self.batch_size:
            return None

        episodes = self.replay_buffer.sample(self.batch_size)

        total_loss = 0.0
        n_steps = 0

        for episode in episodes:
            obs_seq = episode["obs"]        # list of (n_agents, obs_dim)
            actions_seq = episode["actions"]  # list of (n_agents,)
            rewards_seq = episode["rewards"]  # list of scalars
            next_obs_seq = episode["next_obs"]
            dones_seq = episode["dones"]
            states_seq = episode["states"]
            next_states_seq = episode["next_states"]

            T = len(obs_seq)
            hidden = self.agent_net.init_hidden(1).to(self.device)
            target_hidden = self.target_agent_net.init_hidden(1).to(self.device)

            # Stack hidden for all agents
            hiddens = hidden.expand(self.n_agents, -1).contiguous()
            target_hiddens = target_hidden.expand(self.n_agents, -1).contiguous()

            for t in range(T):
                obs_t = obs_seq[t].to(self.device)         # (n_agents, obs_dim)
                actions_t = actions_seq[t].to(self.device)  # (n_agents,)
                reward_t = rewards_seq[t]
                next_obs_t = next_obs_seq[t].to(self.device)
                done_t = dones_seq[t]
                state_t = states_seq[t].to(self.device).unsqueeze(0)
                next_state_t = next_states_seq[t].to(self.device).unsqueeze(0)

                # Current Q values
                q_vals = []
                new_hiddens = []
                for i in range(self.n_agents):
                    q, h = self.agent_net(obs_t[i].unsqueeze(0), hiddens[i].unsqueeze(0))
                    q_vals.append(q.squeeze(0)[actions_t[i]])
                    new_hiddens.append(h.squeeze(0))
                hiddens = torch.stack(new_hiddens).detach()

                chosen_q = torch.stack(q_vals).unsqueeze(0)  # (1, n_agents)
                q_total = self.mixer(chosen_q, state_t)

                # Target Q values
                with torch.no_grad():
                    target_q_vals = []
                    new_target_hiddens = []
                    for i in range(self.n_agents):
                        tq, th = self.target_agent_net(
                            next_obs_t[i].unsqueeze(0),
                            target_hiddens[i].unsqueeze(0)
                        )
                        target_q_vals.append(tq.squeeze(0).max())
                        new_target_hiddens.append(th.squeeze(0))
                    target_hiddens = torch.stack(new_target_hiddens)

                    target_max_q = torch.stack(target_q_vals).unsqueeze(0)
                    target_q_total = self.target_mixer(target_max_q, next_state_t)

                    target = reward_t + self.gamma * (1 - done_t) * target_q_total

                loss = (q_total - target) ** 2
                total_loss += loss
                n_steps += 1

        total_loss = total_loss / n_steps
        self.optimizer.zero_grad()
        total_loss.backward()
        nn.utils.clip_grad_norm_(self.params, 10.0)
        self.optimizer.step()

        self.update_count += 1
        if self.update_count % self.target_update_interval == 0:
            self.target_agent_net.load_state_dict(self.agent_net.state_dict())
            self.target_mixer.load_state_dict(self.mixer.state_dict())

        return total_loss.item()

    def save(self, path):
        path = Path(path)
        path.mkdir(parents=True, exist_ok=True)
        torch.save(self.agent_net.state_dict(), path / "agent_net.pt")
        torch.save(self.mixer.state_dict(), path / "mixer.pt")

    def load(self, path):
        path = Path(path)
        self.agent_net.load_state_dict(torch.load(path / "agent_net.pt", weights_only=True))
        self.mixer.load_state_dict(torch.load(path / "mixer.pt", weights_only=True))
        self.target_agent_net.load_state_dict(self.agent_net.state_dict())
        self.target_mixer.load_state_dict(self.mixer.state_dict())
